# Generated by Django 6.0.2 on 2026-03-24 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cedula_cliente_id', models.CharField(max_length=50)),
                ('cedula_barbero_id', models.CharField(max_length=50)),
                ('servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
            options={
                'db_table': 'agenda_cita',
            },
        ),
    ]
