# Generated by Django 6.0.2 on 2026-04-08 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENT', 'Pendiente'), ('CONF', 'Confirmada'), ('CANC', 'Cancelada')], default='PENT', max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cedula_barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_barbero', to=settings.AUTH_USER_MODEL)),
                ('cedula_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_cliente', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
            ],
            options={
                'db_table': 'agenda_cita',
            },
        ),
    ]
