# Generated by Django 6.0.2 on 2026-03-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENT', 'Pendiente'), ('CONF', 'Confirmada'), ('CANC', 'Cancelada')], default='PENT', max_length=20),
        ),
    ]
