# Generated by Django 6.0.2 on 2026-03-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuarios_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgendaBarbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_barbero', models.CharField(db_column='cedula_barbero', max_length=50)),
                ('dia', models.CharField(max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'agenda_agendabarbero',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('id_servicio', models.IntegerField()),
                ('cedula_cliente_id', models.CharField(max_length=50)),
                ('cedula_barbero_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'agenda_cita',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_minutos', models.IntegerField()),
                ('id_barberia', models.IntegerField()),
                ('id_especialidad', models.IntegerField()),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
    ]
