# Generated by Django 6.0.2 on 2026-03-12 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('id_servicio', models.IntegerField()),
                ('cedula_barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_barbero', to='agenda.usuario')),
                ('cedula_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_cliente', to='agenda.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaBarbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cedula_barbero', models.ForeignKey(db_column='cedula_barbero', on_delete=django.db.models.deletion.CASCADE, to='agenda.usuario')),
            ],
        ),
    ]
