# Generated by Django 6.0.2 on 2026-03-24 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cita',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
