# Generated by Django 6.0.2 on 2026-03-15 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendabarbero',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cita',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
