# Generated by Django 6.0.2 on 2026-04-06 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barberias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_minutos', models.IntegerField()),
                ('barberia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='barberias.barberia')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='barberias.especialidad')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
    ]
