# Generated by Django 6.0.2 on 2026-04-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(default='Activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Barbero', 'Barbero'), ('Admin', 'Administrador')], default='Cliente', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
