"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

import os
from pathlib import Path
from decouple import config
import dj_database_url # <--- IMPORTANTE PARA RENDER

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# ===============================
# ALLOWED HOSTS CONFIGURATION
# ===============================
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Render te da esta variable automáticamente en producción
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Si tienes un frontend en Vercel, luego puedes agregar su dominio aquí también


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt.token_blacklist',
    # Terceros
    'rest_framework',
    'corsheaders',
    "django_filters",
    # Apps propias
    'usuarios',
    'barberias',
    'barberos',
    'agenda',
    'cita',
    'servicios',
    'pagos',
    'calificacion',
]

AUTH_USER_MODEL = 'usuarios.Usuario'

# DRF CONFIGURATION
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# ===============================
# MIDDLEWARE
# ===============================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # <--- NUEVO: Para estáticos en Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# ===============================
# DATABASE CONFIGURATION
# ===============================

# Si estamos en Render (DEBUG=False) y tenemos una URL de base de datos, usamos PostgreSQL
if not DEBUG and config('DATABASE_URL', default=None):
    DATABASES = {
        'default': dj_database_url.config(
            default=config('DATABASE_URL'),
            conn_max_age=600
        )
    }
# De lo contrario (en tu PC), usamos SQLite por defecto para desarrollo
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }                          

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True

# ===============================
# STATIC FILES CONFIGURATION
# ===============================
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # <--- Carpeta donde Render guarda los estáticos
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' # <--- Compresión para producción

# ===============================
# CORS & CSRF CONFIGURATION
# ===============================
# Autorizamos orígenes locales y los túneles que ya tenías
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://84q1s5d2-5173.use2.devtunnels.ms",
]

# Cuando despliegues en Vercel, agrega la URL de Vercel a esta lista
# CORS_ALLOWED_ORIGINS.append("https://tu-proyecto-en-vercel.vercel.app")

CORS_ALLOW_ALL_ORIGINS = True  # Opcional temporal: Si en Render te da problemas de CORS, descomenta esto momentáneamente

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'ngrok-skip-browser-warning',
    'x-tunnel-skip-antiphishing-page',
]

CSRF_TRUSTED_ORIGINS = [
    "https://84q1s5d2-5173.use2.devtunnels.ms",
    "https://lustfully-propeller-unedited.ngrok-free.dev", 
]

# Email Config
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'niokcrack0@gmail.com'
EMAIL_HOST_PASSWORD = 'psprimhdvrovyydm'