# Generated by Django 6.0.5 on 2026-05-06 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barberias', '0001_initial'),
        ('usuarios', '0002_alter_usuario_rol_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberoDetalle',
            fields=[
                ('cedula', models.OneToOneField(db_column='cedula', limit_choices_to={'rol': 'Barbero'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detalle_barbero', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('barberia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barberos', to='barberias.barberia')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barberos', to='barberias.especialidad')),
            ],
            options={
                'db_table': 'barbero_detalle',
            },
        ),
    ]
